### ISSUE TITLE
unhshable type: 'slice'

### ISSUE THREAD

**Issue by Davidnet** [cgarciae/dicto#3]
Look at this traceback:

```
WARNING: datasets not loaded, /root/.dataget/datasets does not exist
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/code/pilotnet/train.py", line 76, in <module>
    @do.fire_options(PARAMS, "params")
  File "/usr/local/lib/python3.5/dist-packages/dicto/api.py", line 171, in fire_options
    dict_ = load(config_path, as_dicto=False)
  File "/usr/local/lib/python3.5/dist-packages/dicto/api.py", line 136, in load
    filepath = os.path.realpath(filepath)
  File "/usr/lib/python3.5/posixpath.py", line 372, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
TypeError: unhashable type: 'slice'
```

**Comment by cgarciae** [comment]
Can you print `PARAMS`?

**Comment by cgarciae** [comment]
Do you have the latest version?
